name = "jachtseizoen"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "GAME_DO", class_name = "GameDO" },
  { name = "ID_GENERATOR", class_name = "IdGenerator"}
]

[[migrations]]
tag = "v1"
new_classes = ["GameDO"]

[[migrations]]
tag = "v2"
new_classes = ["IdGenerator"]